### PR TITLE
Fix: Body text not updating on revisit with linked confidence sliders (fixes #101)

### LINKED ISSUE #101: Disabled Body text still displayed
### Subject of the issue/enhancement/features
If the 2nd of the linked confidence sliders is visited first, then the 1st confidence slider is visited, answered and response submitted the Disabled Body text is still displayed when revisiting the 2nd linked confidence slider.

If however this is completed in the correct order, i.e. 1st confidence slider visited, answered and response submitted and then the 2nd linked confidence slider visited the correct Body text is displayed on the 2nd confidence slider.

### Your environment
* version (AT v0.11.1/Framework v5.31.27)
* which browser and its version - all browsers
* device(s) + operating system(s) MacOS

### Steps to reproduce
Tell us how to reproduce this issue.
As above

### Expected behaviour
Tell us what should happen - Irrelevant of the order visited, if the first linked confidence slider is answered and response submitted the 2nd of the linked confidence sliders should not display the Disabled Body text and display the correct Body text.

### Actual behaviour
Tell us what happens instead: If the 2nd of the linked confidence sliders is visited first, then the 1st confidence slider is visited, answered and response submitted the Disabled Body text is still displayed when revisiting the 2nd linked confidence slider. These confidence sliders are linked correctly as per the screenshot the slider displays the answer (2) from the initial linked confidence slider, but also the Disabled Body text.

If however this is completed in the correct order, i.e. 1st confidence slider visited, answered and response submitted and then the 2nd linked confidence slider visited the correct Body text is displayed on the 2nd confidence slider.

### PR DESCRIPTION
**Pull request by joe-allen-89**
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Link the PR to the original issue)
#101 

[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
### Fix
* Body text not updating on revisit with linked confidence sliders (fixes #101)

### CODE REVIEW

File: js/ConfidenceSliderModel.js [hunk 1]
```diff
@@ -111,6 +115,19 @@ export default class ConfidenceSliderModel extends SliderModel {
...
+    this.set('_isEnabled', (linkedModel.get('_isSubmitted') === true));
+    this.set('_linkedModelSelectedIndex', linkedModel.get('_selectedItem').index);
+    this.checkCanSubmit();
+  }
+
+  _listenToLinkedModel() {
+    this.listenTo(this.linkedModel, {
+      'change:_isSubmitted': this.onLinkedSubmittedChanged
+    });
+  }
```
Comment (oliverfoster) [inline js/ConfidenceSliderModel.js:129]: Line 119: `this.set('body', this.get('originalBody'));` 
This line assumes that the model is submitted and sets `body = originalBody`, you can see this in contrast to line 152 `this.set('body', this.get('disabledBody'));` which sets to `disabledBody` if not submitted .

Line 120: `(linkedModel.get('_isSubmitted') === true)`
This checks if the model is submitted or not and sets `_isEnabled` accordingly, as does line 151 with `if (!this.linkedModel.get('_isSubmitted')) { this.set('_isEnabled', false); }`

Line 154 and Line 121: `this.set('_linkedModelSelectedIndex', linkedModel.get('_selectedItem').index);`
These are identical.


```suggestion
  updateFromLinkedModel() {
    const isSubmitted = this.linkedModel.get('_isSubmitted');
    this.set('body', isSubmitted ? this.get('originalBody') : this.get('disabledBody'));
    this.set('_isEnabled', isSubmitted);
    if (isSubmitted) {
      this.set('_linkedModelSelectedIndex', this.linkedModel.get('_selectedItem').index);
    }
    this.checkCanSubmit();
  }

  _listenToLinkedModel() {
    this.listenTo(this.linkedModel, 'change:_isSubmitted', this.updateFromLinkedModel);
  }
```

File: js/ConfidenceSliderModel.js [hunk 2]
```diff
@@ -129,6 +146,13 @@ export default class ConfidenceSliderModel extends SliderModel {
       _scaleStart: this.linkedModel.get('_scaleStart'),
       _scaleEnd: this.linkedModel.get('_scaleEnd')
     });
+    this._listenToLinkedModel();
+    if (!this.linkedModel.get('_isSubmitted')) {
+      this.set('_isEnabled', false);
+      this.set('body', this.get('disabledBody'));
+    } else {
+      this.set('_linkedModelSelectedIndex', this.linkedModel.get('_selectedItem').index);
+    }
```
Comment (oliverfoster) [inline js/ConfidenceSliderModel.js:155]: Rather than duplicating the code, perhaps call as above:
```suggestion
    this._listenToLinkedModel();
    this.updateFromLinkedModel();
```

**Review by oliverfoster — APPROVED** [review]

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by kirsty-hames — APPROVED** [review]
Working as expected. Testing on Mac Safari, Chrome and FF
