### PR TITLE
Fix: `linkedModel` values not correctly setup on scale when inherited

### LINKED ISSUE #110: `_linkedId` model values not correctly setup on scale
In addition to https://github.com/adaptlearning/adapt-contrib-slider/issues/204, `setupModelItems` is called before `_setupLinkedModel`, meaning the scale can be incorrectly displayed because the range values from the linked model are not used when setting `_items`.

### PR DESCRIPTION
**Pull request by danielghost**
Fixes #110.

### Fix
* Amended execution order so `_setupLinkedModel` is called before `setupModelItems` so model values inherited from `linkedModel` are already set in order for `_items` to be correctly configured.
* Restrict `_scaleStep` to a positive number.

### Update
* Changed `_scaleEnd` schema default from 1 to 10.

### CODE REVIEW

File: js/ConfidenceSliderModel.js [hunk 1]
```diff
@@ -130,7 +132,9 @@ export default class ConfidenceSliderModel extends SliderModel {
   }
 
   _setupLinkedModel() {
-    this.linkedModel = Adapt.components.findWhere({ _id: this.get('_linkedToId') });
+    const linkedToId = this.get('_linkedToId');
+    if (!linkedToId) return;
+    this.linkedModel = Adapt.components.findWhere({ _id: linkedToId });
```
Comment (oliverfoster) [inline js/ConfidenceSliderModel.js:137]:
```suggestion
    this.linkedModel = data.findById(linkedToId);
```

**Review by oliverfoster — CHANGES_REQUESTED** [review]

File: js/ConfidenceSliderModel.js (hunk 1 above)
Comment (danielghost) [reply js/ConfidenceSliderModel.js:137]: This was the code already in use, but can amend accordingly.

**Review by oliverfoster — APPROVED** [review]

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by kirsty-hames — APPROVED** [review]
Works as expected thanks. Testing on Mac Safari, Chrome, FF and iPhone.
