### PR TITLE
issue/51 General refactor, removed offlineStorage code, fixed restore bug

### LINKED ISSUE #51: Not working correctly, unknown reason
image

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #51 

### Fixed
* `onButtonsRendered` bug across session, where restored linked components submit button was disabled
* Added `_scaleStart` and `_scaleEnd` defaults

### Changed
* Reduced feedback generation
* Unnecessary syntax
* For loops

### Removed
* `_linkedToId` value from example.json
* manual `_userAnswer` processing in favour of automatic spoor managed processing
* reference to external extension (adapt-devtools)
* `_linkedModel` from the model json to `linkedModel` as a property of the model class

### CODE REVIEW

File: js/confidenceSliderView.js [hunk 1]
```diff
@@ -1,51 +1,50 @@
...
-
-    super.setupQuestion(this, arguments);
+    super.setupQuestion();
   }
 
   /* override */
   disableQuestion() {
     if (this.model.get('_isReady')) this.setAllItemsEnabled(false);
-    if (this.model.has('_linkedModel')) this.$('.js-btn-action').a11y_cntrl_enabled(false);
+    if (this.model.linkedModel) a11y.toggleEnabled(this.$('.js-btn-action'), false); // this.$('.js-btn-action').a11y_cntrl_enabled(false);
```
Comment (cahirodoherty-learningpool) [inline js/confidenceSliderView.js:26]: Minor: Should this be on a new line and comment be removed?

File: js/confidenceSliderView.js [hunk 2]
```diff
@@ -76,32 +73,19 @@ export default class ConfidenceSliderView extends SliderView {
...
-
   onButtonsRendered(buttonsView) {
+    if (this.buttonsView !== buttonsView) return;
     // necessary due to deferred ButtonsView::postRender
-    const isLinkedModelSubmitted = this.model.get('_linkedModel')?.get('_isSubmitted');
-    if (this.buttonsView !== buttonsView && this.model.get('_isEnabled') && isLinkedModelSubmitted) return;
-    this.$('.js-btn-action').a11y_cntrl_enabled(false);
+    const isLinkedModelSubmitted = this.model.linkedModel?.get('_isSubmitted');
+    if (this.model.get('_isEnabled') && isLinkedModelSubmitted) return;
+    // this.$('.js-btn-action').a11y_cntrl_enabled(false);
```
Comment (eleanor-heath) [inline js/confidenceSliderView.js:87]: commented code needs removed

**Review by eleanor-heath — APPROVED** [review]

**Review by lc-alexanderbenesch — APPROVED** [review]

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀
